version: '3'
networks:
  compose_network:
    driver: bridge
volumes:
  mysql_volume:
    driver: local
services:
  mysql:
    container_name: mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysql_volume:/var/lib/mysql:rw
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: test
    networks:
      - compose_network
    build: ./docker/mysql
  php:
    container_name: php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./:/var/www:rw
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    networks:
      - compose_network
    build: ./docker/php
